spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/edilProject
    username: champ
    password: championShipDb
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    databasePlatform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 604800000